# Generated by Django 4.0.2 on 2022-07-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_alter_blog_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
